#Main section
fight-count: 0
#Time (in seconds) to prepare before the fight during which players will be frozen (if freeze-on-start is true)
countdown-time: 10
#Time after which winners will be either killed or teleported depending on kill-on-fight option
teleport-countdown-time: 3
#If true folder saving info of every fight will be created
create-fights-folder: false
#Enables counting
count-fights: false
#If true plugin will create/connect to ManualTournaments database and save info of every fight
mysql-enabled: false
mysql:
  url: localhost:3306
  username: root
  password: ""

#Settings section
#If true fighters will be able to destroy blocks during the fight
break-blocks: false
#If true fighters will be able to drop their items during the fight
drop-items: false
#If true fighters' items will drop on the ground after their death
drop-on-death: false
#If kill_on_fight_end is false fighters will be teleported to this location, you can specify it using /settings endspawn
fight-end-spawn:
  x:
  y:
  z:
  yaw:
  pitch:
fight-good-luck-enabled: true
#If true fighters will be frozen at the beginning of the fight for countdown-time
freeze-on-start: true
#If true friendly fire inside team will be turned on
friendly-fire: false
#If true winners will be killed after the fight
kill-on-fight-end: true
#If true fighters will be able to place blocks during the fight
place-blocks: false
#List of allowed commands other than /spectate stop you can use while spectating
spectator-allowed-commands: []

#Scoreboard section
#Before starting the fight those have to be specified so that the plugin knows which one to pick
current-kit: ""
current-arena: ""
#Scoreboard team names, functionality to be implemented in future versions
team1: "Red"
team2: "Blue"
#Scoreboard prefix visible on tab and nickname
team1-prefix: "&cRed&r "
team2-prefix: "&9Blue&r "

#Language section
arena-already-exists: "&6An arena with this name already exists"
arena-create: "&7You need to define positions using &e&l/arena (pos1/pos2/spectator)"
arena-lacks-pos1: "&7Arena lacks &e&lpos1"
arena-lacks-pos2: "&7Arena lacks &e&lpos2"
arena-lacks-spectator: "&7Arena lacks &e&lspectator position"
arena-list: "&7Arenas: &e&l"
arena-not-exists: "&6No arena with this name exists"
arena-pos1: "&aPosition for &e&lTeam 1 &r&aset successfully"
arena-pos2: "&aPosition for &e&lTeam 2 &r&aset successfully"
arena-removed: "&aArena removed successfully"
arena-set-correctly: "&7Arena is set correctly"
arena-spectator: "&aPosition for &e&lspectator &r&aset successfully"
arena-spectator-not-set: "&6You need to set &e&lspectator position &r&6before teleporting"
arena-usage: "&7Usage: /arena &e&l(command) (arena name) "
config-options: "&6The only possible options are true and false"
config-updated-successfully: "&aConfig was updated successfully"
current-arena-not-set: "&6You need to set &e&lcurrent arena &r&6using &e&l/settings current_arena &r&6before starting the fight"
current-kit-not-set: "&6You need to set &e&lcurrent kit &r&6using &e&l/settings current_kit &r&6before starting the fight"
fight-concurrent: "&6The fight is already taking place, stop it if you want to start a new one"
fight-death: "&e&l{killer} &r&7killed &e&l{player}"
fighter-error: "&6One or more players can't be found"
fight-good-luck: "&7Good luck :)"
fight-usage: "&7Usage: /fight &e&l(fight type) [fighters]"
#%d is a placeholder for time in seconds
fight-will-start: "&7Fight will start in &e&l%d &r&7seconds"
fight-winners: "&7Congratulations to &e&l{team} &r&7for winning the fight!"

gui-arena-creation-cancelled: "&7Cancelled creating a new arena"
gui-arena-menu-name: "Arena Menu"
gui-arena-lore-color: "&6"
gui-arena-lore-value-color: "&7"
gui-arena-lore-left-click: "&eLeft click to open arena settings"
gui-arena-lore-right-click: "&eRight click to set current arena"
#%s is a placeholder for arena name
gui-arena-settings-menu-name: "Arena %s Settings"
gui-kit-menu-name: "Kit Menu"
gui-settings-menu-name: "Settings Menu"
gui-settings-button-true-lore: "&aTrue"
gui-settings-button-false-lore: "&cFalse"
gui-settings-button-name-color: "&7"
gui-spectator-color: "&e&l"



kit-already-exists: "&6A kit with this name already exists"
kit-given: "&aKit given successfully"
kit-list: "&7Kits: &e&l"
kit-made: "&aKit made successfully"
kit-not-exists: "&6Kit doesn't exist"
kit-removed: "&aKit removed successfully"
kit-set-unbreakable: "&7Items in the inventory set unbreakable"
kit-usage: "&7Usage: /kit &e&l(command/kit name) (kit name)"
not-allowed: "&6You are not allowed to use this command in spectator mode"
not-supported: "&6This command isn't supported for this version"
sender-not-a-player: "&4Sender must be a player!"
settings-usage: "&7Usage: /settings &e&l(setting) (value)"
spectator-started-spectating: "&7Started spectating the fight"
spectator-stopped-spectating: "&7Stopped spectating the fight"
spectator-usage: "&7Usage: /spectate | /spectate &e&lstop"
