fight-count: 0
#If true fighters will be able to destroy blocks during the fight (you have to set WorldGuard flags to prevent arena from being destroyed separately)
break-blocks: false
#If true fighters will be able to place blocks during the fight
place-blocks: false
#Time (in seconds) to prepare before the fight during which players will be frozen (if freeze-on-start is true)
countdown-time: 10
#If true folder saving info for every fight will be created and the names of next files will be based on fight-count (count-fights has to be true and synced for that!)
create-fights-folder: false
count-fights: false
mysql-enabled: false
mysql:
  url: localhost:3306
  username: root
  password: ""
#Switch to true if you have automatic spawn teleport on server join to avoid spectator errors
default-gamemode-on-join: false
#If true fighters will be able to drop their items during the fight
drop-items: false
#If true fighters' items will drop on the ground after their death
drop-on-death: false
#If true fighters will be frozen at the beginning of the fight for countdown-time
freeze-on-start: true
#If true friendly fire inside team will be turned on
friendly-fire: false
#If true winners will be killed after the fight
kill-on-fight-end: true
#If kill_on_fight_end is false fighters will be teleported to location below, you can specify it using /mt_settings endspawn
fight-end-spawn:
  x:
  y:
  z:
  yaw:
  pitch:
#List of allowed commands other than /spectate stop you can use while spectating
spectator-allowed-commands: []
#Valid values are: spectator, survival, adventure, creative
spectator-gamemode: spectator
spectator-visibility: false
#Time after the fight after which winners will be either killed or teleported depending on kill-on-fight option
teleport-countdown-time: 3

#Set these two below using /mt_settings current_kit/arena
current-kit: ""
current-arena: ""
#Scoreboard team names, functionality to be implemented in future versions
team1: "Red"
team2: "Blue"
#Scoreboard prefix visible on tab and nickname
team1-prefix: "&cRed&r "
team2-prefix: "&9Blue&r "

#Language section
arena-already-exists: "&6Arena with this name already exists"
arena-create: "&7You have to define positions using &e&l/arena (pos1/pos2/spectator)"
arena-lacks-pos1: "&7Arena lacks &e&lpos1"
arena-lacks-pos2: "&7Arena lacks &e&lpos2"
arena-lacks-spectator: "&7Arena lacks &e&lspectator position"
arena-list: "&7Arenas: &e&l"
arena-not-exists: "&6Arena with this name doesn't exist"
arena-pos1: "&aPosition for &e&lTeam 1 &r&aset successfully"
arena-pos2: "&aPosition for &e&lTeam 2 &r&aset successfully"
arena-removed: "&aArena removed successfully"
arena-set-correctly: "&7Arena is set correctly"
arena-spectator: "&aPosition for &e&lspectator &r&aset successfully"
arena-spectator-not-set: "&6You have to set &e&lspectator position &r&6before teleporting!"
arena-usage: "&7Usage: /arena &e&l(command) (arena name) "
config-options: "&6Only possible options are true and false"
config-updated-successfully: "&aConfig was updated successfully"
current-arena-not-set: "&6You have to set &e&lcurrent arena &r&6using &e&l/settings current_arena &r&6before starting the fight"
current-kit-not-set: "&6You have to set &e&lcurrent kit &r&6using &e&l/settings current_kit &r&6before starting the fight"
fight-concurrent-arenas: "&6There can only be one fight taking place at the same time"
fight-death: "&e&l{killer} &r&7killed &e&l{player}"
fighter-error: "&6One or more players can't be found"
fight-good-luck: "&7Good luck :)"
fight-good-luck-enabled: true
fight-usage: "&7Usage: /fight &e&l(fight type) [fighters]"
fight-will-start: "&7Fight will start in &e&l"
fight-will-start-seconds: " &r&7seconds"
fight-winners: "&7Congratulations to &e&l{team} &r&7for winning the fight!"
fight-wrong-arguments: "&6The arguments are wrong or don't follow the pattern"
kit-already-exists: "&6Kit with this name already exists"
kit-given: "&aKit given successfully"
kit-list: "&7Kits: &e&l"
kit-made: "&aKit made successfully"
kit-not-exists: "&6Kit doesn't exist"
kit-removed: "&aKit removed successfully"
kit-set-unbreakable: "&7Items in inventory set unbreakable"
kit-usage: "&7Usage: /kit &e&l(command/kit name) (kit name)"
not-allowed: "&6You are not allowed to use this command during spectator mode"
not-supported: "&6This command is not supported for this version"
sender-not-a-player: "&4Sender must be a player"
settings-usage: "&7Usage: /settings &e&l(setting) (value)"
spectator-started-spectating: "&7Started spectating the fight, to leave it use &e&l/spectate stop"
spectator-stopped-spectating: "&7Stopped spectating the fight"
spectator-usage: "&7Usage: /spectate | /spectate &e&lstop"
spectator-wrong-arguments: "&6Invalid gamemode"
