countdown-time: 10
teleport-countdown-time: 3
kill-on-fight-end: true
#if kill-on-fight is false people will be teleported to location below, you can specify it manually or using /ft_settings endspawn
fight-end-spawn:
  x:
  y:
  z:
  yaw:
  pitch:

current-kit: "a"
current-arena: "a"
fight-winners: "Congratulations to: "
fight-winners2: " for winning the fight!"
team1: "Red"
team2: "Blue"
team1-prefix: "Red "
team2-prefix: "Blue "


arena-already-exists: "Arena with this name already exists"
arena-create: "You have to define positions for players and spectators using /arena pos1 (arena name) /arena pos2 (arena name) /arena spectator (arena name)"
arena-lacks-pos1: "Arena lacks pos1"
arena-lacks-pos2: "Arena lacks pos2"
arena-lacks-spectator: "Arena lacks spectator position"
arena-list: "Arenas: "
arena-not-exists: "Arena doesn't exist"
arena-not-set: "You have to set spectator position before teleporting!"
arena-pos1: "Position for player 1 set successfully"
arena-pos2: "Position for player 2 set successfully"
arena-removed: "Arena removed successfully"
arena-set-correctly: "Arena is set correctly"
arena-spectator: "Position for spectator set successfully"
fight-duplicates: "There can't be any duplicates in player names"
fight-good-luck: "Good luck :)"
fight-will-start: "Fight will start in "
fight-will-start-seconds: " seconds"
kit-already-exists: "Kit with this name already exists"
kit-given: "Kit given successfully"
kit-list: "Kits: "
kit-made: "Kit made successfully"
kit-not-exists: "Kit doesn't exist"
kit-removed: "Kit removed successfully"
sender-not-a-player: "Sender must be a player"
wrong-arguments: "Number or values of arguments are incorrect"
