#If true folder saving info for every fight will be created and the names of next files will be based on fight-count (count-fights has to be true for that!)
create-fights-folder: false
count-fights: false
#Switch to true if you have automatic spawn teleport on server join but not this option on to avoid spectator errors
default-gamemode-on-join: false
fight-count: 0
#Time (in seconds) to prepare before the fight during which players will be frozen (if freeze-on-start is true)
countdown-time: 10
#Time after the fight after which winners will be either killed or teleported depending on kill-on-fight option
teleport-countdown-time: 3
#If true fighters will be able to drop their items during the fight
drop-items: false
#If true fighters will be able to destroy blocks during the fight (you have to set WorldGuard flags to prevent arena from being destroyed separately)
break-blocks: false
#If true fighter's items will drop on the ground after their death
drop-on-death: false
#If true fighters will be frozen in the beginning of the fight for countdown-time: seconds
freeze-on-start: true
#If true friendly fire inside team will be turned on
friendly-fire: false
#If true winners will be killed after the fight
kill-on-fight-end: true
#If kill_on_fight_end is false fighters will be teleported to location below, you can specify it manually or using /mt_settings endspawn
fight-end-spawn:
  x:
  y:
  z:
  yaw:
  pitch:


#Set these two below using /mt_settings current_kit/arena
current-kit: ""
current-arena: ""
fight-winners: "Congratulations to {team} for winning the fight!"
#Team names (for now they don't do anything)
team1: "Red"
team2: "Blue"
#Prefix visible on tab and nickname
team1-prefix: "Red "
team2-prefix: "Blue "

#Language section
arena-already-exists: "Arena with this name already exists"
arena-create: "You have to define positions for players and spectators using /arena pos1 (arena name) /arena pos2 (arena name) /arena spectator (arena name)"
arena-lacks-pos1: "Arena lacks pos1"
arena-lacks-pos2: "Arena lacks pos2"
arena-lacks-spectator: "Arena lacks spectator position"
arena-list: "Arenas: "
arena-not-set: "You have to set spectator position before teleporting!"
arena-pos1: "Position for player 1 set successfully"
arena-pos2: "Position for player 2 set successfully"
arena-removed: "Arena removed successfully"
arena-set-correctly: "Arena is set correctly"
arena-spectator: "Position for spectator set successfully"
config-options: "Only possible options are true and false"
config-updated-successfully: "Config was updated successfully"
current-arena-not-set: "You have to set current arena using /settings current_arena before starting the fight"
current-kit-not-set: "You have to set current kit using /settings current_kit before starting the fight"
fight-duplicates: "There can't be any duplicates in player names"
fight-good-luck: "Good luck :)"
#The value between is second
fight-will-start: "Fight will start in "
fight-will-start-seconds: " seconds"
kit-already-exists: "Kit with this name already exists"
kit-given: "Kit given successfully"
kit-list: "Kits: "
kit-made: "Kit made successfully"
kit-not-exists: "Kit doesn't exist"
kit-removed: "Kit removed successfully"
kit-set-unbreakable: "Items in inventory set unbreakable"
not-allowed: "You are not allowed to use this command during spectator mode"
sender-not-a-player: "Sender must be a player"
#List of allowed commands other than /spectate stop you can use while spectating
spectator-allowed-commands: []
#Valid values are: spectator, survival, adventure, creative
spectator-gamemode: spectator
spectator-started-spectating: "Started spectating the fight, to leave it use /spectate stop"
spectator-stopped-spectating: "Stopped spectating the fight"
spectator-visibility: false
spectator-wrong-arguments: "Invalid gamemode"
