main: net.flex.ManualTournaments.Main
name: ManualTournaments
version: 1.2.1
description: Plugin you can use to make manual tournaments
api-version: 1.13
load: POSTWORLD
author: Wolren
website: ""
commands:
  manualtournaments_arena:
    aliases:
      - mt_arena
      - mta
      - arena
    permission: mt.arena
    permission-message: "You don't have permission to use that command"
    usage: "Usage: /arena [list|create|remove|teleport|validate...]"
  manualtournaments_fight:
    aliases:
      - mt_fight
      - mtf
      - fight
    permission: mt.fight
    permission-message: "You don't have permission to use that command"
    usage: "Usage: /fight [player1] [player2]..."
  manualtournaments_kit:
    aliases:
      - mt_kit
      - mtk
      - kit
    permissions: mt.kit
    permission-message: "You don't have permission to use that command"
    usage: "Usage: /kit [kit name] / [list|unbreakable|create|remove|give]"
  manualtournaments_settings:
    aliases:
      - mt_settings
      - mts
      - settings
    permission: mt.settings
    permission-message: "You don't have permission to use that command"
    usage: "Usage: /settings [current_arena|current_kit...]"
  manualtournaments_spectate:
    aliases:
      - mt_spectate
      - mt_spec
      - spec
      - spectate
    permission: mt.spectate
    permission-message: "You have to have spectator permission to use this command!"
    usage: "Usage: /spectate"
    default: true
permissions:
  mt.arena:
    description: Allows for creating and managing arenas
  mt.fight:
    description: Allows for starting the fight between players
  mt.kit:
    description: Allows for creating and managing kits
  mt.settings:
    description: Allows for changing settings
  mt.spectate:
    description: Allows for spectating arenas
  mt.*:
    description: Permission allowing using all ManualTournaments commands
    children:
      mt.arena: true
      mt.fight: true
      mt.kit: true
      mt.settings: true
      mt.spectate: true