main: net.flex.ManualTournaments.Main
name: ManualTournaments
version: 1.0
description: Plugin you can use to make manual tournaments
author: Wildbot
api-version: 1.19
website: ""
commands:
  manualtournaments_arena:
    aliases:
      - mt_arena
      - mta
      - arena
    permission: mt.arena
    permission-message: ""
    usage: "Usage: /arena [create|list|remove...]"
  manualtournaments_fight:
    aliases:
      - mt_fight
      - mtf
      - fight
    permission: mt.fight
    permission-message: ""
    usage: "Usage: /fight [player1] [player2]"
  manualtournaments_kit:
    aliases:
      - mt_kit
      - mtk
      - kit
    permissions: mt.kit
    permission-message: ""
    usage: "Usage: /kit [create|list|remove...]"
  manualtournaments_settings:
    aliases:
      - mt_settings
      - mts
      - settings
    permission: mt.settings
    permission-message: ""
    usage: "Usage: /settings [current_arena|current_kit...]"
  manualtournaments_spectate:
    aliases:
      - mt_spectate
      - mt_spec
      - spec
      - spectate
    permission: mt.spectate
    permission-message: "You have to have mt.spectate permission to use this command!"
    usage: "Usage: /spectate"
permissions:
  mt.arena:
    description: Allows creating and managing arenas
  mt.fight:
    description: Allows starting the fight between players
  mt.kit:
    description: Allows creating and managing kits
  mt.settings:
    description: Allows changing settings
  mt.spectate:
    description: Allows spectating arenas
  mt.*:
    description: Permission allowing using all ManualTournaments commands
    children:
      mt.arena: true
      mt.fight: true
      mt.kit: true
      mt.settings: true
      mt.spectate: true