api-version: 1.18
main: net.flex.FlexTournaments.Main
name: FlexTournaments
version: 1.0
author: Wildbot
description: FlexTournaments
commands:
  flextournaments_arena:
    aliases:
      - ft_arena
      - fta
  flextournaments_fight:
    aliases:
      - ft_fight
      - ftf
  flextournaments_kit:
    aliases:
      - ft_kit
      - ftk
  flextournaments_settings:
    aliases:
      - ft_settings
      - fts