api-version: 1.18
main: net.flex.FlexTournaments.Main
name: FlexTournaments
version: 1.0
author: Wildbot
description: FlexTournaments
commands:
  flextournaments_arena:
    aliases:
      - ft_arena
  flextournaments_fight:
    aliases:
      - ft_fight
  flextournaments_kit:
    aliases:
      - ft_kit
  flextournaments_settings:
    aliases:
      - ft_settings