main: net.flex.ManualTournaments.Main
name: ManualTournaments
version: 1.0
author: Wildbot
description: ManualTournaments
commands:
  manualtournaments_arena:
    aliases:
      - mt_arena
      - mta
    permission: mt.arena, mt.*
  manualtournaments_fight:
    aliases:
      - mt_fight
      - mtf
    permission: mt.fight, mt.*
  manualtournaments_kit:
    aliases:
      - mt_kit
      - mtk
    permission: mt.kit, mt.*
  manualtournaments_settings:
    aliases:
      - mt_settings
      - mts
    permission: mt.settings, mt.*